[versions]
agp = "8.0.2"
atomicfu = "0.21.0"
compose = "1.4.0"
imageLoader = "1.4.0"
kotlin = "1.8.20"
markdown = "0.4.1"

[libraries]
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
jetbrains-markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
image-loader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "imageLoader" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }

[bundles]

