[versions]
agp = "8.2.0-beta06"
compose = "1.5.2"
imageLoader = "1.6.7"
kotlin = "1.9.10"
markdown = "0.5.1"
maven-publish = "0.25.2"

[libraries]
jetbrains-markdown = { module = "org.jetbrains:markdown", version.ref = "markdown" }
image-loader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "imageLoader" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[bundles]

